"""empty message

Revision ID: 4472850b2e4e
Revises: e75dc9f626cb
Create Date: 2025-02-13 22:52:39.928643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4472850b2e4e'
down_revision = 'e75dc9f626cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_age'), ['age'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_age'))
        batch_op.drop_column('last_seen')
        batch_op.drop_column('create_at')
        batch_op.drop_column('avatar_hash')
        batch_op.drop_column('about_me')
        batch_op.drop_column('location')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
