"""Remove unique constraint from age

Revision ID: e9089a3c483f
Revises: 4472850b2e4e
Create Date: 2025-02-14 00:18:33.510371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9089a3c483f'
down_revision = '4472850b2e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_age')
        batch_op.create_index(batch_op.f('ix_user_age'), ['age'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_age'))
        batch_op.create_index('ix_user_age', ['age'], unique=True)

    # ### end Alembic commands ###
